import java.util.function.Function

String applicationPluginId = libs.plugins.android.application.get().pluginId

private static <T, R> R with(T receiver, Function<T, R> block) {
    return block.apply(receiver);
}

subprojects { project ->
    project.afterEvaluate { evaluatedProject ->
        with(evaluatedProject.pluginManager) { pm ->
            if (pm.hasPlugin(applicationPluginId)) {
                android.lintOptions {
                    lintConfig file("$rootDir/linters/androidLint/config.xml")
                }
            }
        }
    }
}
